openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: >-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification. 
    You can find out more about

    Swagger at [https://swagger.io](https://swagger.io). In the third iteration
    of the pet store, we've switched to the design first approach!

    You can now help us improve the API whether it's by making changes to the
    definition itself or to the code.

    That way, with time, we can improve the API in general, and expose some of
    the new features in OAS3.


    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then
    click
    [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml).
    Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu
    option!_


    Some useful links:

    - [The Pet Store
    repository](https://github.com/swagger-api/swagger-petstore)

    - [The source API definition for the Pet
    Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: 127.0.0.1

tags:
  - name: user
    #description: Everything about your Pets
    #externalDocs:
    #  description: Find out more
    #  url: http://swagger.io
  
  
  - name: admin
    #description: Everything about your Pets
    #externalDocs:
    #  description: Find out more
    #  url: http://swagger.io
  
  
paths:
  /users/login:
    post:
      tags:
        - user
      responses:
        '200':
          description: successful login
          
  /users/logout:
    post:
      tags:
        - user
      responses:
        '200':
          description: successful logout
  /users/change-password-request:  
    post:
      tags:
        - user
      responses:
        '200':
          description: successful request
  
  /users/change-password-action‬:
    post:
      tags:
        - user
      responses:
        '200':
          description: successful request
  
  /admin/professors‬:
    post:
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      tags:
        - admin
      responses:
        '200':
          description: successful request
  
  /admin/professors/{pk}‬:
    put:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    delete:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    
  /admin/students:
    post:
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      tags:
        - admin
      responses:
        '200':
          description: successful request
  
  /admin/assistants:
    post:
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      tags:
        - admin
      responses:
        '200':
          description: successful request
    
          
  
  /admin/assistant/{pk}‬:
    put:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    delete:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    
  /admin/faculties:
      post:
        tags:
          - admin
        responses:
          '200':
            description: successful request
      get:
        tags:
          - admin
        responses:
          '200':
            description: successful request
  
  /admin/faculty/{pk}:
      post:
        parameters:
          - in: path
            name: pk
            schema:
              type: integer
            required: true
        tags:
          - admin
        responses:
          '200':
            description: successful request
      get:
        parameters:
          - in: path
            name: pk
            schema:
              type: integer
            required: true
        tags:
          - admin
        responses:
          '200':
            description: successful request
  
  /admin/term:
      post:
        tags:
          - admin
        responses:
          '200':
            description: successful request
      get:
        tags:
          - admin
        responses:
          '200':
            description: successful request
  
  
  
