openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: >-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification. 
    You can find out more about

    Swagger at [https://swagger.io](https://swagger.io). In the third iteration
    of the pet store, we've switched to the design first approach!

    You can now help us improve the API whether it's by making changes to the
    definition itself or to the code.

    That way, with time, we can improve the API in general, and expose some of
    the new features in OAS3.


    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then
    click
    [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml).
    Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu
    option!_


    Some useful links:

    - [The Pet Store
    repository](https://github.com/swagger-api/swagger-petstore)

    - [The source API definition for the Pet
    Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: 127.0.0.1
tags:
  - name: user
  - name: term
  - name: admin
  - name: subject
  - name: course
  - name: student
  - name: professor
paths:
  /users/login:
    post:
      tags:
        - user
      responses:
        '200':
          description: successful login
  /users/logout:
    post:
      tags:
        - user
      responses:
        '200':
          description: successful logout
  /users/change-password-request:
    post:
      tags:
        - user
      responses:
        '200':
          description: successful request
  /users/change-password-action‬:
    post:
      tags:
        - user
      responses:
        '200':
          description: successful request
  /admin/professors‬:
    post:
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      tags:
        - admin
      responses:
        '200':
          description: successful request
  /admin/professors/{pk}‬:
    put:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    delete:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
  /admin/students:
    post:
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      tags:
        - admin
      responses:
        '200':
          description: successful request
  /admin/assistants:
    post:
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      tags:
        - admin
      responses:
        '200':
          description: successful request
  /admin/assistant/{pk}‬:
    put:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    delete:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
  /admin/faculties:
    post:
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      tags:
        - admin
      responses:
        '200':
          description: successful request
  /admin/faculty/{pk}:
    post:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
  /admin/term:
    post:
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      tags:
        - admin
      responses:
        '200':
          description: successful request
  /admin/term/{pk}:
    put:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
    delete:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - admin
      responses:
        '200':
          description: successful request
  /subjects:
    post:
      tags:
        - subject
      responses:
        '200':
          description: successful request
    get:
      tags:
        - subject
      responses:
        '200':
          description: successful request
  /subjects/{pk}:
    put:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - subject
      responses:
        '200':
          description: successful request
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - subject
      responses:
        '200':
          description: successful request
    delete:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - subject
      responses:
        '200':
          description: successful request
  /courses:
    post:
      tags:
        - course
      responses:
        '200':
          description: successful request
    get:
      tags:
        - course
      responses:
        '200':
          description: successful request
  /courses/{pk}:
    put:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - course
      responses:
        '200':
          description: successful request
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - course
      responses:
        '200':
          description: successful request
    delete:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - course
      responses:
        '200':
          description: successful request
  /students:
    get:
      tags:
        - student
      responses:
        '200':
          description: successful request
  /students/{pk}:
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
    put:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  /professors:
    get:
      tags:
        - professor
      responses:
        '200':
          description: successful request
  /professors/{pk}:
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - professor
      responses:
        '200':
          description: successful request
    put:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - professor
      responses:
        '200':
          description: successful request
  /terms:
    get:
      tags:
        - term
      responses:
        '200':
          description: successful request
  /term/{pk}:
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - term
      responses:
        '200':
          description: successful request
  /student/{pk}/my-courses:
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  /student/{pk}/pass-courses-report:
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  /student/{pk}/term-courses:
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  /student/{pk}/remaining-terms:
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  /student/{pk}/course-selection/create:
    post:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  /student/{pk}/course-selection:
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  /student/{pk}/course-selection/check:
    post:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  /student/{pk}/course-selection/submit:
    post:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  /student/{pk}/course-selection/send-form:
    post:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  /professor/{pk}/students-selection-forms:
    post:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - professor
      responses:
        '200':
          description: successful request
  /professor/{pk}/students-selection-forms/{s-pk}:
    post:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
        - in: path
          name: s-pk
          schema:
            type: integer
          required: true
      tags:
        - professor
      responses:
        '200':
          description: successful request
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
        - in: path
          name: s-pk
          schema:
            type: integer
          required: true
      tags:
        - professor
      responses:
        '200':
          description: successful request
  
  
  /student/{pk}/course-substitution/create:
    post:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
          
  /student/{pk}/course-substitution:
    get:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
  
  /student/{pk}/course-substitution/check:
    post:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
          
  /student/{pk}/course-substitution/submit:
    post:
      parameters:
        - in: path
          name: pk
          schema:
            type: integer
          required: true
      tags:
        - student
      responses:
        '200':
          description: successful request
          
  
